### PR TITLE
OSX fix for `outputclue.sh` on `tree` branch

### PR DESCRIPTION
**Pull request by conroywhitney**
This was a fun game, thank you for making it!

Using OSX 10.6.8, I had to change `outputclue.sh` on the `tree` branch to find the next clue. Namely:

* Changing `md5sum` to `md5`
* Changing `base64 -d` to `openssl base64 -d`

I am not able to test these changes on any other operating systems.

### CODE REVIEW

**Comment by riqpe** [comment]
Calling md5 breaks GNU/Linux compatibility. Use openssl md5 instead. Note that where md5sum prints md5 hash first and the source second, openssl md5 prints source first, md5 hash second and so you also need to change awk to print the second word piped to it.

```diff
diff --git a/outputclue.sh b/outputclue.sh
index c0a3939..52266c4 100755
--- a/outputclue.sh
+++ b/outputclue.sh
@@ -13,7 +13,7 @@ if [ "$file" = "nextclue_input.cpp" ];then
   if [ ${merges} ]; then 
     while read p; do 
       for w in $p;do 
-        if [ `echo $w | md5 | awk '{print $1}'` = $bug ];then 
+        if [ `echo $w | openssl md5 | awk '{print $2}'` = $bug ];then 
           echo -e $mesg; 
           exit; 
         fi; 
```

**Comment by hgarc014** [comment]
as @riqpe  stated your above code breaks GNU/Linux. However, if the code @riqpe works on OSX i'd be happy to add it.

**Comment by conroywhitney** [comment]
Thanks @hgarc014 and @riqpe. I ceated pull #11 to address these suggestions.

On OSX, I needed to keep `awk '{print $1}'` instead of your suggestion of `awk '{print $2}'`. However, I am unable to test this on GNU Linux.

**Comment by hgarc014** [comment]
leaving `awk '{print $1}'` on Linux causes the answer to always be given, unless it is set to `awk '{print $2}'`

**Comment by riqpe** [comment]
Suggest using `sed "s/^.*= *//"` instead of awk to support both.

**Pull request closed without merging**
